### ISSUE TITLE
Regarding the issue of data labels

### ISSUE THREAD

**Issue by shuaifengj** [Claud1234/CLFT#4]
Thank you for your contributions in this field. I would like to ask why the semantic segmentation labels for our data are projected from LiDAR semantic labels instead of using the labels from images. Is it because the Waymo dataset does not have semantic labels for images, or is there another reason?

**Comment by Claud1234** [comment]
@shuaifengj  Hi. You are right, in Waymo Dataset, also in nuScene, the annotation labels of the objects are made from the LiDAR point cloud. Precisely speaking, human-made labels are the 3D bounding boxes in LiDAR point clouds, then assign the points in this bounding box with the corresponding object labels. This kind of human-made-labeling method is understandable in the perspective of labor resource. 

But if the network's strategy is not processing the LiDAR points directly (for example our work, we adopt the strategy to project the LiDAR points as the camera plane image), the only way to acquire the ground-truth-annotation is projecting the manual-labeled-points on the images as well. Though this will cause the issue that the annotation is not a perfect object mask. Here is an example of the Waymo Dataset we used in this work. 
![image](https://github.com/user-attachments/assets/4f561b98-2a02-4caa-80eb-f88258998a01)

The solution to this problem is using the dataset that has dense LiDAR point clouds, which is why we use Waymo dataset. From this pic, you can see it is relatively denser. 
![image](https://github.com/user-attachments/assets/d90a4f98-96fb-4a31-b9cb-1d13c4c581e8)

Compared with the nuScene that use Velodyne VLP-32 LiDAR which only has the 32 channels in vertical. Here is an example:
![image](https://github.com/user-attachments/assets/eefd6f04-0a75-469c-b40c-4aa73e42de2f)

So the Waymo dataset is always the priority for 2D semantic segmentation task. 
Hope I answered your question.

**Comment by shuaifengj** [comment]
Thank you for your prompt response amidst your busy schedule. Is the reason for not directly using image labels that the Waymo dataset does not have 2D semantic segmentation labels? If my own dataset has 2D semantic labels, would using 2D semantic labels be better?

**Comment by Claud1234** [comment]
@shuaifengj 

>>
Is the reason for not directly using image labels that the Waymo dataset does not have 2D semantic segmentation labels?
<<
Exactly. Actually as far as I know not too many large scale open datasets provide the semantic labels made from the images directly. Because making the contour on images are way more expensive than draw bounding boxes. 

>>
If my own dataset has 2D semantic labels, would using 2D semantic labels be better?
<<
It would be perfect, especially you want to train the models.

**Comment by shuaifengj** [comment]
got it, thank you for the explanation.

**Comment by shuaifengj** [comment]
Got it, thank you for the explanation.
